# Generated by Django 4.2.9 on 2024-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
